server:
  port: 8081
spring:
  application:
    name: reggie_take_out
    #Redis相关配置
  redis:
    host: 39.106.77.183
    port: 6379
    password: 565034470
    database: 0 #操作的是0号数据库
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  cache:
    redis:
      time-to-live: 1800000 #设置缓存时间为1800s--30min
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.106.77.183:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 565034470
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
# Linux目录 --> /usr/local/WorkSpace/temp/
  path: /usr/local/WorkSpace/temp/
# windows目录 --> D:\WorkSpace\temp\
  accessKeyId: LTAI5tMHJgr
  accessKeySecret: Hv0t8CKG2FO
  accessKeyId_: 6cdhZeC4sW5hU
  accessKeySecret_: 8IIR28QhHNf0FpusiRg

