server:
  port: 8082
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.106.77.183:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 565034470
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
# Linux目录 --> /usr/local/WorkSpace/temp
  path: /usr/local/WorkSpace/temp
# windows目录 --> D:\WorkSpace\temp\
  accessKeyId: LTAI5tMHJgr
  accessKeySecret: Hv0t8CKG2FO
  accessKeyId_: 6cdhZeC4sW5hU
  accessKeySecret_: 8IIR28QhHNf0FpusiRg